import { SITE } from "@/lib/seo";
import Link from "next/link";

const linkClass =
  "text-fg underline decoration-border underline-offset-4 hover:text-accent-teal";

/** Frozen snapshot of Version 1.5 (effective August 6, 2026). Do not edit except to correct a transcription error. */
export function ClientServiceTermsV1_5() {
  return (
    <div className="space-y-8">
      <header className="legal-page-header space-y-4 border-b border-border pb-8 overflow-visible">
        <h1 className="legal-page-title">
          Website and Application Services Agreement
        </h1>
        <p className="text-lg text-fg-muted leading-relaxed">Managed websites, hosted applications, domains, maintenance, and related digital services</p>
        <p className="text-sm text-fg-muted">Effective date: August 6, 2026</p>
        <p className="text-sm text-fg-muted">Version: 1.5</p>
        <p className="text-sm text-fg-muted">Operator: Ragusto</p>
        <p className="text-sm font-medium tracking-wide text-fg-muted">FOR BUSINESS AND COMMERCIAL CUSTOMERS ONLY</p>
        <p className="text-xs tracking-[0.3em] text-fg-muted uppercase">RAGUSTO</p>
      </header>
      <div className="rounded-lg border border-border bg-bg-muted/40 p-5 text-sm text-fg-muted leading-relaxed">
        <p className="text-sm text-fg-muted leading-relaxed">Important commercial terms: An optional non-refundable Project Reservation Payment may apply before subscription activation. The Project Reservation Payment does not immediately begin the Website Subscription or Initial Term. Customer Activation Approval is required before the Website Subscription begins. Conditional Activation Approval is available. Where a Project Reservation Payment was made, the first monthly service period receives a 100% subscription-invoice discount and counts as month 1; eleven full-price monthly service periods follow. The Initial Term consists of 12 consecutive monthly service periods. Subscription Activation and public launch are separate events. Monthly billing is a payment arrangement and does not make the Initial Term cancel-anytime.</p>
      </div>
      <section className="space-y-4">
        <h2 className="legal-section-title">1. Parties, Commercial Purpose, and Agreement Structure</h2>
        <p className="text-fg-muted leading-relaxed">This Website and Application Services Agreement (the &quot;Agreement&quot;) is between Ragusto and each person or organization that accepts this Agreement in connection with purchasing or using Services (the &quot;Customer&quot;).</p>
        <p className="text-fg-muted leading-relaxed">The Customer represents that it acquires the Services primarily for business or commercial purposes and not for personal, family, or household purposes.</p>
        <p className="text-fg-muted leading-relaxed">This Agreement contains the general terms that apply to all Customers. The Stripe product name and Product Description displayed before purchase, the checkout or hosted invoice page, the initial invoice, and any written confirmation issued by Ragusto identify the applicable Service, price, recurring and one-time charges, and selected optional features. Those records form part of the Agreement only for those commercial details. If a commercial detail conflicts, the Product Description in effect when the Customer completes the applicable checkout or pays the applicable invoice controls for that detail unless Ragusto and the Customer later agree in writing; the remaining terms continue to apply.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">2. Electronic Acceptance and Authority</h2>
        <p className="text-fg-muted leading-relaxed">The Customer may accept this Agreement by checking an acceptance box, electronically signing, confirming acceptance in writing, completing a Stripe checkout that links to or expressly references this Agreement, paying an invoice that links to or expressly references this Agreement, or using another electronic process designated by Ragusto.</p>
        <p className="text-fg-muted leading-relaxed">Payment of a Project Reservation Payment through a checkout or invoice that links to or expressly references this Agreement constitutes acceptance of the reservation and preliminary-work terms, immediate non-refundability, the first-month economic treatment described in this Agreement, the Activation Approval process, intellectual-property provisions, confidentiality provisions, dispute provisions, and payment and cancellation provisions applicable before activation. Payment of a Project Reservation Payment does not itself constitute Activation Approval and does not itself begin the Website Subscription, the Initial Term, or recurring billing.</p>
        <p className="text-fg-muted leading-relaxed">The individual accepting confirms that they have authority to bind the Customer, have had an opportunity to review the applicable Product Description and this Agreement, authorize the disclosed one-time and recurring charges, and intend to create a binding contract.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may retain electronic records of acceptance, including the accepted Agreement version, the Product Description displayed at acceptance, the date, email address, checkout or invoice identifiers, payment records, and related communications. Later edits to a Product Description do not retroactively change the commercial details accepted for an existing Initial Term.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">3. Definitions</h2>
        <p className="text-fg-muted leading-relaxed">&quot;Activation Approval&quot; means the Customer&apos;s clear affirmative authorization for Ragusto to activate the applicable Website Subscription or recurring Application service. Activation Approval may be unconditional, conditional upon completion of specifically identified final requirements, or given verbally and documented in accordance with this Agreement.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Application&quot; means any software, web application, portal, dashboard, calculator, configurator, booking system, automation, AI-enabled feature, integration, database interface, or other interactive functionality supplied by Ragusto.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Approval Confirmation&quot; means written communication sent by Ragusto to the Customer documenting an oral Activation Approval or Conditional Activation Approval, including the applicable Service, approval date, recurring price, identified conditions, and intended activation process.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Conditional Activation Approval&quot; means an Activation Approval under which the Customer authorizes activation once Ragusto completes specifically identified final changes, requirements, or launch conditions. Once those identified conditions are completed, no additional approval concerning the same conditions is required.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Completion and Activation Notice&quot; means written notice sent by Ragusto after an unconditional Activation Approval or after Ragusto completes the conditions identified in a Conditional Activation Approval. The notice identifies the Service, Subscription Activation Date, recurring price, first-month treatment, and any remaining non-material launch work.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Customer Content&quot; means trademarks, logos, written copy, photographs, videos, product or service information, customer data, and other proprietary materials supplied by or owned by the Customer.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Customer Service Data&quot; means information submitted to, generated through, stored in, or processed by a Website or Application, including contact-form submissions, account information, appointment details, uploads, transaction records, and usage data.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Initial Term&quot; means the first 12 consecutive monthly service periods of the Website Subscription beginning on the Subscription Activation Date. A separate Application has a different minimum term only where its Product Description clearly states that term before purchase.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Launch Date&quot; means the date on which the Website or applicable Application is first made publicly or operationally available.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Managed Website Subscription&quot; describes Ragusto&apos;s ongoing management of the hosted Website under the Website Subscription. It does not by itself determine domain ownership or mean that domain registration, renewal, or management is included in the Website Subscription price.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Minimum Committed Fees&quot; means an amount equal to 12 monthly Website Subscription fees for the Initial Term, excluding one-time fees, usage fees, taxes, domain fees, third-party charges, and separate Application fees unless the Product Description clearly states that a charge is bundled into the Website Subscription price. Where a Project Reservation Payment applies, the Project Reservation Payment satisfies the economic cost of service period 1, and the remaining Minimum Committed Fees consist of 11 full-price monthly Website Subscription payments.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Product Description&quot; means the service description displayed by Ragusto or its payment processor before purchase that identifies the applicable Service and its principal commercial terms.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Project Reservation Payment&quot; means a one-time payment equal to one monthly Managed Website Subscription fee that Ragusto may optionally collect before the Website Subscription begins. The Project Reservation Payment is immediately non-refundable after successful payment, subject only to the narrow refund exceptions stated in this Agreement. It reserves Ragusto production capacity, authorizes preliminary and customer-specific project work, does not itself begin the Website Subscription, does not itself begin the Initial Term, does not itself constitute Activation Approval, economically prepays the first monthly Website Subscription service period, and is reflected at subscription activation by applying a 100%-off-once discount to the first subscription invoice. It does not create a duplicate credit, free additional month, cash balance, or refundable customer balance.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Ready for Activation&quot; means that the principal design, pages, and agreed core functionality are substantially complete and reasonably capable of public launch or operational use, subject only to minor revisions, customer-controlled requirements, domain or DNS connection, third-party propagation, optional enhancements, or other non-material remaining work.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Services&quot; means the Website Subscription, Applications, domain services, one-time build or launch work, hosting, maintenance, support, and any other service purchased or provided under this Agreement and identified in a Product Description, checkout or hosted invoice page, invoice, or written confirmation from Ragusto.</p>
        <p className="text-fg-muted leading-relaxed">Without a Project Reservation Payment, &quot;Subscription Activation Date&quot; means the date on which the Customer has accepted this Agreement, given Activation Approval, obtained valid recurring-payment authorization, and the first monthly Website Subscription payment is successfully processed.</p>
        <p className="text-fg-muted leading-relaxed">With a Project Reservation Payment, &quot;Subscription Activation Date&quot; means the date identified in the Completion and Activation Notice after the Customer has given unconditional Activation Approval or Ragusto has completed the specifically identified requirements contained in a Conditional Activation Approval. On that date, the recurring Website Subscription is established, the 100%-off-once first-month discount is applied, the first monthly Website Subscription service period begins, the discounted service period counts as month 1, and the following 11 monthly service periods are billed at the normal recurring price. Payment of the Project Reservation Payment alone does not begin the Initial Term.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Website&quot; means the customer-specific website designed, developed, hosted, licensed, maintained, or supported by Ragusto.</p>
        <p className="text-fg-muted leading-relaxed">&quot;Website Subscription&quot; means the hosted and managed website service described in Section 10, including continued access to the Website, hosting, routine technical maintenance, reasonable operational support, appropriate security and dependency updates, correction of reproducible technical defects within existing functionality, and reasonable minor content updates, subject to the limitations and exclusions in this Agreement.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">4. Pre-Subscription Preview and Unpaid Work</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto may prepare a non-public concept, prototype, staging site, or other preview before receiving payment. Unless otherwise agreed in writing, the prospective customer is not required to subscribe merely because a preview was prepared, and Ragusto is not required to continue unpaid work indefinitely.</p>
        <p className="text-fg-muted leading-relaxed">Before Ragusto begins customer-specific unpaid preview work beyond a preliminary consultation or generic demonstration, the prospective customer must accept a separate Pre-Subscription Preview Authorization or equivalent written authorization. A decision by Ragusto to begin limited work before receiving that acceptance does not transfer rights or waive Ragusto&apos;s ownership protections.</p>
        <p className="text-fg-muted leading-relaxed">Unless the accepted Preview Authorization states otherwise, the no-cost preview is limited to one initial concept and one reasonable refinement. Additional concepts, repeated revisions, expanded pages, Applications, integrations, or material scope changes may require subscription activation or a separately approved fee.</p>
        <p className="text-fg-muted leading-relaxed">All preliminary designs, layouts, code, concepts, prototypes, staging environments, and related materials remain Ragusto property. Before paid activation, they are supplied for evaluation only and may not be copied, published, commercially used, distributed, provided to another developer, reverse engineered, or recreated.</p>
        <p className="text-fg-muted leading-relaxed">The prospective customer retains ownership of its supplied materials and grants Ragusto a limited licence to use those materials to prepare and present the preview.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may password-protect, watermark, limit, suspend, or remove a preview. Ragusto may stop unpaid work where the prospect becomes unresponsive, changes scope materially, requests work beyond the authorized preview scope, or no longer appears reasonably likely to proceed.</p>
        <p className="text-fg-muted leading-relaxed">Where no Project Reservation Payment applies, the Customer may still receive a preview or have substantial work completed before subscription activation. In that pathway, the first monthly Website Subscription fee is charged at activation, the Initial Term consists of 12 consecutive monthly service periods, all 12 monthly service periods are charged at the applicable recurring price, and activation may occur before public launch while minor revisions or launch preparation remain.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">5. Scope of Services</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto will provide the Services described in the applicable Product Description and this Agreement. A Product Description may identify website strategy, design, development, final revisions, hosting, licensing, maintenance, support, domain services, Applications, integrations, content services, or other digital work.</p>
        <p className="text-fg-muted leading-relaxed">Services may be purchased before, at the same time as, during, or after a Website launch. Additional Services require a separate Product Description, checkout or hosted invoice page, invoice, or written approval from Ragusto that identifies the additional fee before work begins.</p>
        <p className="text-fg-muted leading-relaxed">Statements in marketing materials, informal discussions, demonstrations, or preliminary estimates do not expand the scope unless they are reflected in the applicable Product Description or later confirmed in writing by Ragusto.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">6. Subscription Activation, Customer Approval, and Launch</h2>
        <h3 className="legal-subsection-title">6.1 Activation Approval required</h3>
        <p className="text-fg-muted leading-relaxed">The Website Subscription must not begin merely because Ragusto unilaterally determines that the Website or Application is Ready for Activation. A valid Customer Activation Approval is required. Ragusto will not treat Customer silence as the original affirmative Activation Approval.</p>
        <h3 className="legal-subsection-title">6.2 Written Activation Approval</h3>
        <p className="text-fg-muted leading-relaxed">Activation Approval may be given through email, text message, customer portal, another written electronic communication, or another written communication that reasonably identifies the Customer and clearly communicates approval. Approval language does not need to use a specific legal phrase. Examples include &quot;Approved to proceed,&quot; &quot;The website is approved,&quot; &quot;It is good to launch,&quot; &quot;Go ahead with the subscription,&quot; &quot;Once the following listed changes are completed, it is approved to launch,&quot; or &quot;After those final changes, we are good to go.&quot; Ragusto will interpret approval according to the communication&apos;s reasonable meaning and surrounding project context.</p>
        <h3 className="legal-subsection-title">6.3 Verbal Activation Approval</h3>
        <p className="text-fg-muted leading-relaxed">Activation Approval may be given during a telephone call, video call, or in-person conversation. Where approval is verbal, Ragusto must send an Approval Confirmation to the Customer&apos;s authorized email address documenting the date of the oral approval; the applicable Website or Application; whether the approval was unconditional or conditional; the specifically identified conditions; the recurring monthly price; the Project Reservation Payment treatment, where applicable; the intended activation process; and the Customer&apos;s opportunity to identify an inaccuracy.</p>
        <p className="text-fg-muted leading-relaxed">The Customer has at least two business days to dispute the accuracy of an Approval Confirmation. Customer silence is not itself the original Activation Approval. The Customer&apos;s affirmative oral statement is the approval. Ragusto&apos;s email documents the approval. Ragusto may rely on the documented oral approval if the Customer does not timely identify an inaccuracy. Where the Customer timely disputes whether approval was given or identifies a material inaccuracy, Ragusto will pause activation and address the disputed record in good faith.</p>
        <h3 className="legal-subsection-title">6.4 Conditional Activation Approval</h3>
        <p className="text-fg-muted leading-relaxed">The Customer may give Conditional Activation Approval, including statements such as &quot;Once these final changes are completed, the website is good to launch.&quot; The approval conditions must be reasonably identifiable. Ragusto may document verbally stated conditions through an Approval Confirmation. The Customer does not need to repeat its approval once the listed conditions are completed. Ragusto may send a Completion and Activation Notice after completing the listed conditions.</p>
        <p className="text-fg-muted leading-relaxed">New requests made after Conditional Activation Approval are not automatically added to the activation conditions. New preferences, optional enhancements, additional pages, additional functionality, out-of-scope requests, or changed business requirements do not postpone activation unless Ragusto expressly agrees. Minor wording, spacing, image, styling, or aesthetic preferences do not invalidate the approval where the identified conditions were completed. Customer-controlled failure to provide information, access, credentials, content, domain access, or third-party approval does not necessarily invalidate the approval where Ragusto has completed the work reasonably possible.</p>
        <p className="text-fg-muted leading-relaxed">Before activation, the Customer may object by identifying an incomplete approval condition or a material defect that reasonably prevents the intended launch or operation. Ragusto will assess any timely material objection in good faith.</p>
        <h3 className="legal-subsection-title">6.5 Completion and Activation Notice</h3>
        <p className="text-fg-muted leading-relaxed">The Completion and Activation Notice must be sent to the Customer&apos;s authorized email address; identify the applicable Website or Application; identify the Activation Approval relied upon; confirm completion of any Conditional Activation Approval requirements; identify the Subscription Activation Date; state the recurring monthly price; state whether a Project Reservation Payment applies; state that the first monthly subscription invoice will receive a 100% discount where applicable; state that the discounted service period counts as month 1 where applicable; state that the following 11 monthly service periods will be billed at the full recurring price where applicable; and identify any remaining non-material launch work.</p>
        <p className="text-fg-muted leading-relaxed">Unless the Customer expressly authorizes immediate activation, Ragusto will ordinarily set the Subscription Activation Date at least two business days after sending the Completion and Activation Notice. This notice period does not require further approval and permits the Customer only to identify an incomplete agreed activation condition or a material defect that reasonably prevents launch or operation.</p>
        <h3 className="legal-subsection-title">6.6 Subscription Activation Date</h3>
        <p className="text-fg-muted leading-relaxed">Without a Project Reservation Payment, the Subscription Activation Date occurs when the Customer has accepted this Agreement, given Activation Approval, obtained valid recurring-payment authorization, and the first monthly Website Subscription payment is successfully processed.</p>
        <p className="text-fg-muted leading-relaxed">With a Project Reservation Payment, the Subscription Activation Date is the date identified in the Completion and Activation Notice after unconditional Activation Approval or completion of the specifically identified requirements in a Conditional Activation Approval. On that date, the recurring Website Subscription is established, the 100%-off-once first-month discount is applied, the first monthly Website Subscription service period begins, the discounted service period counts as month 1, and the following 11 monthly service periods are billed at the normal recurring price.</p>
        <p className="text-fg-muted leading-relaxed">The Initial Term and monthly billing begin on the Subscription Activation Date whether or not the Website is publicly live. Payment of the Project Reservation Payment alone does not begin the Initial Term.</p>
        <h3 className="legal-subsection-title">6.7 Activation before launch and public launch</h3>
        <p className="text-fg-muted leading-relaxed">Subscription Activation and public launch are separate operational events. Activation may occur immediately before public launch and may occur while DNS propagation, domain connection, SSL issuance, or other non-material launch preparation remains. Ragusto may request separate operational confirmation concerning the exact public-launch moment. That operational confirmation does not necessarily require a second Subscription Activation Approval. A valid Conditional Activation Approval remains effective once its listed requirements are completed. New preferences or new scope do not automatically postpone activation.</p>
        <p className="text-fg-muted leading-relaxed">The Customer may activate the Website Subscription while final revisions, configuration, testing, content implementation, domain setup, or other launch preparations remain outstanding.</p>
        <h3 className="legal-subsection-title">6.8 Pre-launch subscription services</h3>
        <p className="text-fg-muted leading-relaxed">Before the Launch Date, the Website Subscription includes the continued design, development, revision, configuration, testing, launch preparation, hosting preparation, and licensing work reasonably required within the accepted scope. After launch, it includes the Managed Website Services described in Section 10 and any optional service clearly identified in the Product Description.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will ordinarily request Activation Approval after the principal pages, design, and agreed core functionality are available for review, even if minor revisions, content, integrations, testing, or domain configuration remain. Ragusto will not ordinarily connect the Website to the Customer&apos;s live production domain before the initial amount due has been paid.</p>
        <h3 className="legal-subsection-title">6.9 Launch conditions and delays</h3>
        <p className="text-fg-muted leading-relaxed">Launch dates are estimates unless Ragusto expressly guarantees a date in writing. Customer-requested changes, missing content, delayed approvals, missing account access, domain or DNS issues, third-party dependencies, new scope, or other matters outside Ragusto&apos;s reasonable control do not pause billing, extend the Initial Term, or postpone payment obligations after the Subscription Activation Date.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">7. Initial 12-Month Minimum Commitment</h2>
        <p className="text-fg-muted leading-relaxed">The Website Subscription carries a minimum commitment of 12 consecutive monthly service periods beginning on the Subscription Activation Date. The Minimum Committed Fees are the agreed minimum price for the front-loaded design and development work, reserved service capacity, hosted licence, and continuing availability of the Website Subscription during the Initial Term.</p>
        <p className="text-fg-muted leading-relaxed">Where a Project Reservation Payment applies, service period 1 receives a 100% discount on the subscription invoice, service period 1 still counts as month 1, the Project Reservation Payment is the economic payment for service period 1, service periods 2 through 12 are billed at full price, the first-month discount does not create a free additional month, the discount does not shorten the Initial Term, and the Customer receives 12 consecutive monthly service periods. The Project Reservation Payment plus the following 11 full-price monthly Website Subscription payments equal the Minimum Committed Fees. The Project Reservation Payment itself does not begin the Initial Term.</p>
        <p className="text-fg-muted leading-relaxed">Where no Project Reservation Payment applies, the Initial Term consists of 12 consecutive monthly service periods, all charged at the applicable recurring monthly price displayed in the Product Description and confirmed on the initial invoice.</p>
        <p className="text-fg-muted leading-relaxed">The Initial Term is paid in monthly instalments at the recurring monthly price displayed in the Product Description and confirmed on the applicable invoice. Monthly billing is a payment arrangement and does not convert the Initial Term into a cancel-anytime monthly agreement.</p>
        <p className="text-fg-muted leading-relaxed">If the Customer voluntarily requests cancellation, stops using the Website, requests an early takedown, or otherwise chooses not to continue during the Initial Term after the Subscription Activation Date, the Minimum Committed Fees remain payable on the original monthly schedule unless Ragusto agrees in writing to an early-release amount or other arrangement.</p>
        <p className="text-fg-muted leading-relaxed">If Ragusto terminates because of the Customer&apos;s uncured material breach, Ragusto may claim the unpaid Minimum Committed Fees as the agreed minimum price, less costs that Ragusto reasonably avoids because of early termination. Ragusto will not recover more than it would have received if the Initial Term had been completed.</p>
        <p className="text-fg-muted leading-relaxed">Future Minimum Committed Fees do not accrue after the effective termination date if the Customer terminates for Ragusto&apos;s uncured material breach or if Ragusto terminates without Customer breach. Accrued charges and fees for Services already provided remain payable.</p>
        <p className="text-fg-muted leading-relaxed">A Project Reservation Payment applied under this Agreement counts toward the Minimum Committed Fees as the economic payment for the first monthly service period. One-Time Build and Launch Fees, separate Application fees, domain fees, and other one-time charges remain additional unless expressly stated otherwise in the Product Description or a written confirmation from Ragusto.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">8. Month-to-Month Renewal and Cancellation After the Initial Term</h2>
        <p className="text-fg-muted leading-relaxed">After the Initial Term, the Website Subscription automatically renews for successive one-month service periods.</p>
        <p className="text-fg-muted leading-relaxed">The Customer may cancel at any time after completing the Initial Term. No 30-day advance notice is required. A cancellation request received through an authorized cancellation method before Stripe or another payment processor processes the next renewal takes effect at the end of the then-current paid service period, and no further Website Subscription renewal will be charged.</p>
        <p className="text-fg-muted leading-relaxed">If the next renewal has already been processed before Ragusto receives the cancellation request, cancellation takes effect at the end of that newly paid service period.</p>
        <p className="text-fg-muted leading-relaxed">Payments already processed are non-refundable and not prorated except where required by law or expressly agreed by Ragusto in writing. Immediate deactivation at the Customer&apos;s request does not create a refund for the unused portion of a paid period.</p>
        <p className="text-fg-muted leading-relaxed">
          Authorized cancellation methods are the Stripe Customer Portal where cancellation is enabled, email to{" "}
          <a className={linkClass} href={`mailto:${SITE.email}`}>jacob@ragusto.com</a>, or another method expressly designated by Ragusto. Email cancellation requests are measured in Eastern Time. Ragusto will send or make available a cancellation confirmation; if the Customer does not receive confirmation within two business days, the Customer should follow up, but proof of timely receipt through an authorized method remains controlling.
        </p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">9. Fees, Billing, and Payment</h2>
        <h3 className="legal-subsection-title">9.1 Recurring authorization</h3>
        <p className="text-fg-muted leading-relaxed">Recurring charges remain subject to valid authorization through Stripe or another payment processor. Ragusto may use a stored payment method only where it was validly configured for future use. The processor or card issuer may require additional authentication. The Customer must reasonably cooperate with required authentication or updated payment details. A technical payment requirement may delay payment collection or activation. Removing or replacing a payment method does not terminate contractual payment obligations after subscription activation. The Project Reservation Payment itself does not create the recurring subscription and does not by itself authorize recurring payments.</p>
        <p className="text-fg-muted leading-relaxed">After subscription activation, the Customer authorizes Ragusto and its payment processor to charge the payment method on file for recurring fees, disclosed one-time fees, usage charges, third-party pass-through charges, applicable taxes, and other amounts displayed in the applicable Product Description, checkout or hosted invoice page, invoice, or later approved by the Customer in writing.</p>
        <h3 className="legal-subsection-title">9.2 Optional Non-Refundable Project Reservation Payment</h3>
        <p className="text-fg-muted leading-relaxed">Ragusto may optionally collect a Project Reservation Payment before the Website Subscription begins. The Project Reservation Payment equals one monthly Website Subscription fee, is payable before subscription activation, immediately reserves Ragusto production capacity, and authorizes onboarding, discovery, requirements gathering, domain-name consultation, content collection, planning, scheduling, design, development, testing, and launch preparation.</p>
        <p className="text-fg-muted leading-relaxed">The Project Reservation Payment is non-recurring. It does not immediately begin the Website Subscription, does not immediately begin the Initial Term, does not itself constitute Activation Approval, and does not guarantee a particular completion date or Launch Date. It is immediately non-refundable after successful payment, subject only to refund where required by applicable law, the payment was duplicated or unauthorized, or Ragusto permanently declines or is unable to provide the engagement for reasons not caused by the Customer.</p>
        <p className="text-fg-muted leading-relaxed">The Project Reservation Payment is not a refundable deposit, security, security deposit, customer funds held in trust, store credit, customer credit balance, loan, cash-equivalent balance, or transferable credit. It cannot be transferred, assigned, redeemed for cash, or used for an unrelated engagement without Ragusto&apos;s express written agreement.</p>
        <p className="text-fg-muted leading-relaxed">The Project Reservation Payment remains non-refundable where the Customer changes its mind; cancels the engagement; abandons the project; becomes unresponsive; fails to provide content, credentials, access, approvals, instructions, or feedback; delays the project; refuses to proceed; refuses public launch; chooses another service provider; changes its business plans; experiences internal personnel, ownership, budget, or operational changes; no longer wants the Website or Application; or otherwise elects not to continue before subscription activation. Ragusto may reschedule production where the Customer delays the project.</p>
        <p className="text-fg-muted leading-relaxed">The Project Reservation Payment economically applies to service period 1 through the first-month subscription discount and cannot create two separate credits or discounts for service period 1. It does not itself authorize or begin recurring billing.</p>
        <h3 className="legal-subsection-title">9.3 Customer withdrawal before activation</h3>
        <p className="text-fg-muted leading-relaxed">The Customer may withdraw from the engagement before the Subscription Activation Date by providing written notice to Ragusto. Where the Customer withdraws before activation, the recurring Website Subscription will not begin, the 12-month Initial Term will not begin, future recurring Website Subscription payments will not become payable solely because the Project Reservation Payment was made, the Project Reservation Payment remains non-refundable, and the Customer does not receive source code, repositories, production files, editable design files, unfinished work, Reusable Materials, or other Ragusto intellectual property.</p>
        <p className="text-fg-muted leading-relaxed">After the Subscription Activation Date, cancellation and termination are governed by the Initial-Term provisions in Sections 7 and 8.</p>
        <h3 className="legal-subsection-title">9.4 First-month subscription discount</h3>
        <p className="text-fg-muted leading-relaxed">Where a Project Reservation Payment applies, on the Subscription Activation Date Ragusto applies a 100%-off-once discount to the first Website Subscription invoice. The first invoice may show a zero amount due. The corresponding monthly period is active Website Subscription service period 1. The Project Reservation Payment is the economic payment for service period 1. Eleven full-price monthly service periods follow.</p>
        <p className="text-fg-muted leading-relaxed">The discount does not create a free month, does not shorten the Initial Term, total Website Subscription service remains 12 monthly service periods, and total base price remains equal to 12 monthly fees. Where an administrative or processor error causes a duplicate first-month charge, Ragusto will correct the invoice or apply an equivalent adjustment. The discount is not cash, a refundable balance, or a customer credit balance.</p>
        <h3 className="legal-subsection-title">9.5 Optional One-Time Build and Launch Fee</h3>
        <p className="text-fg-muted leading-relaxed">Where the Product Description or initial invoice identifies a One-Time Build and Launch Fee, it is payable with the first Website Subscription payment at activation unless otherwise stated. It compensates Ragusto for customer-specific strategy, design, development, configuration, testing, and launch preparation performed before and around activation.</p>
        <p className="text-fg-muted leading-relaxed">The fee is non-recurring and does not transfer ownership of the Website, source code, design systems, reusable components, or other Ragusto intellectual property. It is separate from a Project Reservation Payment unless the Product Description clearly states otherwise.</p>
        <p className="text-fg-muted leading-relaxed">If a One-Time Build and Launch Fee is not disclosed in the Product Description or initial invoice before payment, no such fee will be charged for the initial Website activation.</p>
        <h3 className="legal-subsection-title">9.6 Non-refundable amounts</h3>
        <p className="text-fg-muted leading-relaxed">Except where required by law, the payment was duplicated or unauthorized, or Ragusto permanently declines or is unable to provide the engagement for reasons not caused by the Customer, the Project Reservation Payment is immediately non-refundable after successful payment.</p>
        <p className="text-fg-muted leading-relaxed">Except where required by law or where Ragusto materially breaches the Agreement and fails to cure the breach, other one-time fees and subscription payments already processed are non-refundable because they compensate for work performed, reserved capacity, access, hosting, licensing, and ongoing service availability.</p>
        <h3 className="legal-subsection-title">9.7 Failed and overdue payments</h3>
        <p className="text-fg-muted leading-relaxed">Ragusto or its processor may retry failed payments and send payment-recovery communications. Ragusto may suspend Services after providing reasonable notice of a failed or overdue payment and may suspend immediately where reasonably necessary to address fraud, unlawful activity, security threats, abuse, or material risk.</p>
        <p className="text-fg-muted leading-relaxed">Suspension does not cancel the Agreement or eliminate amounts owing. The Customer is responsible for reasonable collection costs. Beginning 30 days after the due date, overdue amounts may bear simple interest at 18 percent per annum, calculated monthly and not compounded, or the maximum rate permitted by law if lower.</p>
        <h3 className="legal-subsection-title">9.8 Chargebacks and disputes</h3>
        <p className="text-fg-muted leading-relaxed">The Customer should contact Ragusto promptly to resolve a billing concern before initiating a chargeback. The Customer must not knowingly submit a false or misleading payment dispute. Ragusto may suspend Services while a payment dispute is pending.</p>
        <h3 className="legal-subsection-title">9.9 Taxes and price changes</h3>
        <p className="text-fg-muted leading-relaxed">Fees exclude applicable taxes unless stated otherwise. Ragusto will not increase the recurring Website Subscription price during the Initial Term except for approved additional Services or disclosed third-party pass-through costs. After the Initial Term, Ragusto may change recurring fees with at least 30 days&apos; written notice.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">10. Nature of the Website Subscription and Customer Licence</h2>
        <p className="text-fg-muted leading-relaxed">The Website Subscription is a hosted and managed website service and licence, not a sale of source code or a transfer of ownership in Ragusto systems.</p>
        <h3 className="legal-subsection-title">10.1 Included Managed Website Services</h3>
        <p className="text-fg-muted leading-relaxed">Unless the Product Description clearly states otherwise, an active and fully paid Website Subscription includes continued access to the hosted Website; hosting infrastructure selected by Ragusto; routine technical maintenance; reasonable support relating to the operation of the Website; security and dependency updates that Ragusto considers appropriate; correction of reproducible technical defects within the Website&apos;s existing agreed functionality; and reasonable minor content updates under Section 10.2.</p>
        <h3 className="legal-subsection-title">10.2 Routine Minor Content Updates</h3>
        <p className="text-fg-muted leading-relaxed">Reasonable minor content updates may include correcting or replacing limited amounts of existing wording; updating business hours, contact details, staff information, pricing, or service descriptions; replacing an existing photograph, graphic, or downloadable file with Customer-supplied or properly licensed material; adding a limited amount of content to an existing section where no material redesign is required; and other comparable administrative changes that Ragusto reasonably determines can be completed within the Website&apos;s existing design, structure, and functionality.</p>
        <p className="text-fg-muted leading-relaxed">Minor content updates are subject to reasonable frequency, volume, scheduling, and technical feasibility. They do not include new pages or substantial new sections; redesigns or material layout changes; new functionality, Applications, integrations, forms, or databases; extensive rewriting or copywriting; photography, graphic design, or media production; large product, inventory, article, gallery, or data uploads; search-engine optimization or advertising campaigns; legal, privacy, accessibility, or regulatory drafting; repeated urgent revisions; or remediation required by unauthorized Customer or third-party changes.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may identify a request as additional work before beginning it and may require the Customer&apos;s written approval of an additional fee. The Customer is responsible for the accuracy, legality, and licensing of all replacement content and materials it supplies.</p>
        <h3 className="legal-subsection-title">10.3 Domain Arrangements</h3>
        <p className="text-fg-muted leading-relaxed">The term &quot;Managed Website Subscription&quot; describes Ragusto&apos;s ongoing management of the hosted Website. It does not by itself determine domain ownership or mean that domain registration, renewal, or management is included in the Website Subscription price.</p>
        <p className="text-fg-muted leading-relaxed">Depending on the Product Description or a written domain confirmation from Ragusto: (a) the Customer may own and manage the domain while granting Ragusto the delegated access reasonably required to connect and operate the Website; (b) the Customer may own the domain while authorizing Ragusto to manage specified DNS, renewal, security, or administrative functions; or (c) Ragusto may register, hold, renew, and manage the domain for the Customer&apos;s exclusive business use in accordance with Section 14.</p>
        <p className="text-fg-muted leading-relaxed">If no domain arrangement is expressly identified, the Customer remains responsible for domain ownership and renewal, and Ragusto receives only the delegated technical access reasonably required to connect and operate the Website. Domain registration, renewal, and management may be bundled into the Website Subscription price or billed separately only where the Product Description or a written domain confirmation from Ragusto clearly says so.</p>
        <h3 className="legal-subsection-title">10.4 Customer Licence</h3>
        <p className="text-fg-muted leading-relaxed">While the applicable subscription is active, paid, and in compliance, Ragusto grants the Customer a limited, non-exclusive, non-transferable right to use the hosted Website for the Customer&apos;s business.</p>
        <p className="text-fg-muted leading-relaxed">The Customer may not copy or extract source code, resell or sublicense the Website, provide the implementation to another developer, reverse engineer Ragusto systems, or represent Ragusto intellectual property as Customer-owned.</p>
        <p className="text-fg-muted leading-relaxed">The licence ends when the applicable subscription ends unless the parties enter a separate written buyout or ownership-transfer agreement.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">11. Customer Content and Customer Responsibilities</h2>
        <p className="text-fg-muted leading-relaxed">As between the parties, the Customer retains ownership of Customer Content. The Customer grants Ragusto a non-exclusive, worldwide, royalty-free licence to host, reproduce, modify, format, display, transmit, and otherwise process Customer Content as reasonably necessary to provide, secure, maintain, and support the Services.</p>
        <p className="text-fg-muted leading-relaxed">The Customer represents that it owns or is authorized to use Customer Content, that Ragusto&apos;s authorized use will not infringe third-party rights, and that the content and business claims are accurate, lawful, and adequately substantiated.</p>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for its products, services, pricing, advertising claims, legal notices, privacy notices, cookie notices, accessibility obligations, industry-specific requirements, and regulatory compliance. Ragusto does not provide legal, tax, accounting, or regulatory advice.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may refuse or remove content that it reasonably believes is unlawful, infringing, deceptive, harmful, or inconsistent with the Agreement.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">12. Ragusto Intellectual Property</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto retains all rights in source code, software, Applications, reusable code, templates, frameworks, libraries, design systems, components, animations, deployment systems, technical methods, documentation, internal processes, tools, know-how, and improvements.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto develops and uses reusable materials, systems, and methods in providing websites, Applications, and related services. These may include templates, frameworks, source-code libraries, components, modules, page structures, section arrangements, grids, navigation and footer patterns, typography and spacing systems, colour-application methods, user-interface patterns, responsive behaviours, animations, interaction patterns, workflows, technical architecture, development processes, and general design techniques (collectively, &quot;Reusable Materials&quot;).</p>
        <p className="text-fg-muted leading-relaxed">No copyright assignment, source-code transfer, or ownership transfer occurs by implication, payment of fees, custom development, domain transfer, hosting on a Customer domain, or termination. Any transfer requires a separate written agreement expressly signed by Ragusto.</p>
        <h3 className="legal-subsection-title">12.1 Reusable Materials, Similarity, and Non-Exclusivity</h3>
        <p className="text-fg-muted leading-relaxed">Reusable Materials may have been created or used before the Customer&apos;s engagement, may be developed or improved while providing Services to the Customer, and may be reused, adapted, modified, licensed, commercialized, or incorporated into work supplied to other customers.</p>
        <p className="text-fg-muted leading-relaxed">Unless Ragusto expressly agrees otherwise in writing, the Customer does not receive exclusivity over the Website&apos;s or Application&apos;s general style, aesthetic direction, overall look and feel, common page types, layouts, section structures, components, functionality, navigation, footer, content-presentation patterns, typography, spacing, colour or grid methodologies, animation or interaction techniques, technical architecture, hosting arrangements, development methods, or other Reusable Materials.</p>
        <p className="text-fg-muted leading-relaxed">The Customer acknowledges that websites, Applications, and services created by Ragusto for other customers may contain elements, features, functionality, layouts, styles, design treatments, or overall characteristics that are similar to those used for the Customer. Similarity resulting from Reusable Materials, common design conventions, industry practices, independently developed work, or Ragusto&apos;s general skills and experience does not constitute a breach of this Agreement and does not create a claim to exclusivity, compensation, ownership, or restriction of Ragusto&apos;s work for others.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will not knowingly reuse or disclose the Customer&apos;s trademarks, logos, trade names, Customer-created written content, photography, video, proprietary artwork, Customer Service Data, confidential information, private business processes, non-public commercial information, or any deliverable expressly confirmed by Ragusto in writing as exclusive, except as authorized by the Customer or otherwise permitted by this Agreement.</p>
        <p className="text-fg-muted leading-relaxed">No exclusivity is granted by implication. Any exclusivity must be set out in a separate written agreement accepted by Ragusto and must identify the specific protected elements, duration, industry or competitive scope, geographic area, and any additional exclusivity fee.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">13. Applications and Additional Digital Services</h2>
        <h3 className="legal-subsection-title">13.1 Application types and timing</h3>
        <p className="text-fg-muted leading-relaxed">An Application may be integrated into the Website, hosted on a subdomain or separate URL, operated independently, or connected to third-party software. Applications may be purchased before, at, during, or after Website launch and may be sold independently of a Website Subscription.</p>
        <h3 className="legal-subsection-title">13.2 Application Product Details</h3>
        <p className="text-fg-muted leading-relaxed">Each Application will have a Product Description identifying its principal function, fees, activation terms, minimum term if any, hosting, maintenance, support, usage limits, third-party dependencies, data requirements, relationship to the Website, and treatment on cancellation. The invoice confirms the charges but does not expand the functionality described before purchase.</p>
        <h3 className="legal-subsection-title">13.3 Application pricing</h3>
        <p className="text-fg-muted leading-relaxed">Application fees may include a one-time design, build, and activation fee; a recurring licence or subscription fee; hosting, maintenance, and support fees; usage-based fees; third-party charges; or a combination.</p>
        <p className="text-fg-muted leading-relaxed">A recurring Application does not automatically share the Website Subscription&apos;s Initial Term. Its term is the term clearly stated in its Product Description. Unless a separate minimum term is clearly stated before purchase, a recurring Application renews month-to-month and may be cancelled before the next billing date.</p>
        <p className="text-fg-muted leading-relaxed">The Project Reservation Payment pathway described in Section 9.2 may apply to an Application only where the applicable Application Product Description expressly adopts that pathway. Ragusto does not automatically impose the Website Subscription&apos;s 12-month Initial Term on every Application.</p>
        <h3 className="legal-subsection-title">13.4 Dependent and independent Applications</h3>
        <p className="text-fg-muted leading-relaxed">The Product Description will identify whether an Application depends on the Website Subscription or is independently hosted and cancellable. Unless clearly identified as independent, an Application incorporated into the Website is considered part of the hosted Website environment and may be disabled when the Website Subscription ends.</p>
        <h3 className="legal-subsection-title">13.5 Application ownership and support</h3>
        <p className="text-fg-muted leading-relaxed">Payment of a one-time or recurring Application fee does not transfer source-code ownership. Maintenance includes only the functionality and support described in the Product Description and does not include new features, major workflow changes, new integrations, data migration, increased infrastructure, or remediation caused by unauthorized changes unless separately approved in writing.</p>
        <h3 className="legal-subsection-title">13.6 AI-enabled functionality</h3>
        <p className="text-fg-muted leading-relaxed">AI-enabled Applications may produce inaccurate, incomplete, outdated, or unexpected outputs. The Customer is responsible for appropriate human review and must not treat AI output as legal, medical, financial, safety-critical, or other professional advice. Ragusto does not guarantee the accuracy or continued availability of third-party AI models.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">14. Domains</h2>
        <h3 className="legal-subsection-title">14.1 Preferred registration structure</h3>
        <p className="text-fg-muted leading-relaxed">Where reasonably practical, the Customer should be listed as the registered domain holder from the outset and should retain ultimate account-recovery control. The Customer may grant Ragusto delegated technical or administrative access for DNS, hosting, security, email, registration, renewal, and related configuration.</p>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for renewal unless the Product Description or a written domain confirmation from Ragusto expressly includes domain renewal and management. The Customer must maintain accurate registrant information and promptly disclose active email, verification, or other DNS dependencies before changes are made.</p>
        <h3 className="legal-subsection-title">14.2 Ragusto-Held and Managed Domain</h3>
        <p className="text-fg-muted leading-relaxed">Where the Product Description or a written domain confirmation from Ragusto identifies a Ragusto-held and managed domain, Ragusto may register or hold the domain through a registrar account controlled by Ragusto and may appear as the registered name holder or account holder. The parties intend that the domain be held for the Customer&apos;s exclusive business use and be transferable to the Customer under this Section.</p>
        <p className="text-fg-muted leading-relaxed">The Customer receives the exclusive contractual right to use that domain for its business while the applicable Domain Registration, Renewal and Management service is active and paid. The recurring domain fee compensates Ragusto for registration, renewals, account administration, DNS management, support, and associated risk; it is not necessarily a direct pass-through of registrar cost.</p>
        <p className="text-fg-muted leading-relaxed">Premium domains, aftermarket purchases, unusually priced extensions, special eligibility requirements, and special acquisition costs are excluded unless disclosed in the Product Description or a written domain confirmation from Ragusto before the Customer approves the charge.</p>
        <h3 className="legal-subsection-title">14.3 Transfer at Customer request</h3>
        <p className="text-fg-muted leading-relaxed">The Customer may request transfer of a Ragusto-held domain at any time. Ragusto will use commercially reasonable efforts to initiate transfer after the Customer pays outstanding domain-related amounts, any disclosed unrecovered acquisition or renewal amount, and direct registrar or transfer charges; creates or identifies a receiving registrar account; provides accurate registrant details; and completes required verification.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will not indefinitely withhold a Customer business domain solely because an unrelated Website or Application invoice is disputed or unpaid. Unrelated payment obligations remain enforceable separately. Ragusto may delay transfer to address fraud, ownership disputes, legal process, abuse, security risks, or registrar requirements.</p>
        <p className="text-fg-muted leading-relaxed">Transfer timing is subject to registrar and registry rules, eligibility requirements, security holds, expiration status, verification, disputes, and transfer locks outside Ragusto&apos;s control. No separate domain buyout fee applies unless it was expressly disclosed in the Product Description or a written domain confirmation before registration or acquisition.</p>
        <h3 className="legal-subsection-title">14.4 Effect of transfer</h3>
        <p className="text-fg-muted leading-relaxed">Domain transfer does not transfer the Website, Application, or source code; does not automatically cancel another Service; and transfers future renewal responsibility to the Customer. The recurring domain-management fee ends when transfer is completed, except for accrued amounts.</p>
        <p className="text-fg-muted leading-relaxed">The parties must coordinate DNS, email, verification, and third-party records. Ragusto is not responsible for disruption caused by undisclosed records, Customer changes, another provider, failure to follow transfer instructions, or an improperly coordinated transfer.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">15. Customer Service Data, Contact Forms, and Privacy</h2>
        <h3 className="legal-subsection-title">15.1 Customer control and responsibility</h3>
        <p className="text-fg-muted leading-relaxed">The Customer determines what Customer Service Data is collected, why it is collected, how it is used, who may access it, and how long it is retained. The Customer is responsible for lawful notices, consent language, marketing practices, access controls, responses to individuals, and compliance with privacy and data-protection laws applicable to its business.</p>
        <h3 className="legal-subsection-title">15.2 Ragusto as service provider</h3>
        <p className="text-fg-muted leading-relaxed">Ragusto may process, transmit, store, or access Customer Service Data only as reasonably necessary to host, operate, secure, maintain, troubleshoot, support, fulfil documented Customer instructions, or comply with law. Ragusto does not acquire ownership of Customer Service Data and will not use it for Ragusto&apos;s independent marketing.</p>
        <p className="text-fg-muted leading-relaxed">Where Ragusto processes Customer Service Data on the Customer&apos;s behalf, Schedule 1 applies as the Data Processing Addendum and Schedule 2 describes baseline security measures. If Ragusto and the Customer sign a separate written data-processing or security agreement containing more specific terms, those terms control for the applicable Service.</p>
        <h3 className="legal-subsection-title">15.3 Sensitive and regulated data</h3>
        <p className="text-fg-muted leading-relaxed">The Customer must not use a Website or Application to collect medical records, government identification numbers, financial-account credentials, precise biometric data, information about minors, or similarly sensitive or regulated information unless Ragusto has expressly agreed in writing to an appropriate technical and contractual arrangement.</p>
        <h3 className="legal-subsection-title">15.4 Security responsibilities, AI tools, and incidents</h3>
        <p className="text-fg-muted leading-relaxed">The Customer must use strong passwords, multi-factor authentication where available, secure authorized devices, and promptly report suspected compromise. Ragusto is not responsible for losses caused by compromised Customer credentials, unauthorized Customer disclosures, or failure to follow reasonable security instructions.</p>
        <p className="text-fg-muted leading-relaxed">Unless separately authorized in writing and subject to an appropriate data-protection arrangement, Ragusto will not intentionally submit Customer Service Data, access credentials, complete payment information, or sensitive confidential information to a generative-AI service.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will notify the Customer without undue delay after becoming aware of actual or reasonably suspected unauthorized access, use, disclosure, alteration, loss, or destruction that materially affects Customer Service Data processed by Ragusto, subject to lawful restrictions and the information reasonably available. Ragusto may provide updates as the investigation develops. The Customer remains responsible for determining and completing its own regulatory notices, individual notifications, and remediation obligations unless the parties agree otherwise in writing.</p>
        <h3 className="legal-subsection-title">15.5 Export and deletion</h3>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for preserving data it needs. On request made before termination or within 30 days afterward, Ragusto may provide one standard export of reasonably accessible Customer Service Data in a commonly available format where technically practicable. Custom migration, transformation, and third-party setup are billable. Ragusto may delete remaining data after the transition period, subject to legal, accounting, security, and backup-retention requirements.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">16. Customer Cooperation, Approvals, and Change Control</h2>
        <p className="text-fg-muted leading-relaxed">The Customer will designate an authorized contact. Ragusto may rely on that person&apos;s instructions, approvals, content, and payment decisions until notified otherwise in writing.</p>
        <p className="text-fg-muted leading-relaxed">The Customer must provide accurate information, materials, access, feedback, and approvals in a timely manner. Customer delays do not suspend billing or extend the Initial Term after the Subscription Activation Date. If the Customer is unresponsive for more than 30 days, Ragusto may pause work, reschedule it, and disclose a reasonable restart fee before resuming.</p>
        <p className="text-fg-muted leading-relaxed">Changes to scope, fees, functionality, delivery obligations, or timing are effective only when confirmed in writing by Ragusto. Requests that materially change the approved design, page count, features, Application requirements, or integrations may require an additional fee disclosed and approved before work begins.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may treat a milestone as accepted for scheduling after written notice and a reasonable response period, but will not activate the Website Subscription without Activation Approval and will not publicly launch the Website without express launch approval or conduct reasonably demonstrating approval for the public-launch moment, including operational confirmation where Ragusto requests it.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">17. Third-Party Services, Accounts, and Technical Changes</h2>
        <p className="text-fg-muted leading-relaxed">Services may depend on hosting providers, databases, payment processors, email services, registrars, stock media, APIs, plugins, open-source software, analytics, AI services, and other third-party products. Third-party products remain subject to their own terms, pricing, licences, limits, and availability.</p>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for charges assigned to Customer-controlled accounts. Ragusto may pass through disclosed third-party charges and may recommend or implement reasonably comparable alternatives if a provider becomes unavailable or unsuitable. Material redevelopment may require additional fees.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may make reasonable technical, security, infrastructure, dependency, and hosting changes that do not materially reduce the core Service.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">18. Hosting, Availability, Backups, and Maintenance</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto will use commercially reasonable efforts to keep hosted Services operational but does not guarantee uninterrupted, error-free, or completely secure availability. Maintenance, Internet failures, security incidents, third-party outages, DNS issues, Customer actions, malicious attacks, and events beyond Ragusto&apos;s control may affect availability.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may maintain backups according to its normal procedures, but the Customer should retain copies of Customer Content and critical business data. Backups are not guaranteed to capture every change or be retained indefinitely.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may perform emergency maintenance without advance notice where reasonably necessary to protect systems, data, users, or third parties.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">19. Portfolio and Publicity</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto may identify the Customer as a client and display public screenshots, recordings, links, or a general description of completed work only where the Customer provides written approval.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will not knowingly disclose confidential information or private Customer Service Data for portfolio purposes.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">20. Confidentiality</h2>
        <p className="text-fg-muted leading-relaxed">Each party will use the other party&apos;s non-public confidential information only for the relationship, protect it with reasonable care, and disclose it only to persons who require it and are subject to confidentiality obligations.</p>
        <p className="text-fg-muted leading-relaxed">Confidential information does not include information that is publicly available without breach, lawfully known before disclosure, lawfully received from another source, independently developed, or required to be disclosed by law. A party compelled to disclose will provide notice where legally permitted.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">21. Disclaimers and No Guaranteed Results</h2>
        <p className="text-fg-muted leading-relaxed">Except for express obligations in this Agreement or the applicable Product Description, the Services are provided on an &quot;as available&quot; basis. To the maximum extent permitted by law, Ragusto disclaims implied warranties and conditions, including merchantability, fitness for a particular purpose, non-infringement, uninterrupted availability, error-free operation, and particular commercial results.</p>
        <p className="text-fg-muted leading-relaxed">Unless Ragusto expressly states otherwise in writing, Ragusto does not guarantee search rankings, traffic, leads, sales, conversion rates, advertising results, accessibility certification, compliance in every jurisdiction, compatibility with every device or browser, or continued availability of third-party products.</p>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for independent legal, privacy, tax, accounting, accessibility, security, and industry-specific review where appropriate.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">22. Customer Indemnity</h2>
        <p className="text-fg-muted leading-relaxed">To the extent caused by a matter within the Customer&apos;s control, the Customer will defend, indemnify, and hold harmless Ragusto and its personnel from third-party claims, damages, liabilities, judgments, settlements, and reasonable legal costs arising from Customer Content; Customer products, services, advertising, or business claims; Customer Service Data; privacy, marketing, or consent practices controlled by the Customer; unlawful Customer conduct; infringement caused by Customer materials or instructions; a domain requested by the Customer; or the Customer&apos;s material breach of the Agreement.</p>
        <p className="text-fg-muted leading-relaxed">The indemnity does not apply to the extent a claim is finally determined to have been caused by Ragusto&apos;s material breach, gross negligence, fraud, or wilful misconduct.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will give prompt notice of an indemnified claim, although delayed notice relieves the Customer only to the extent the delay materially prejudices the defence. The Customer may control the defence with counsel reasonably acceptable to Ragusto, and Ragusto will provide reasonable cooperation at the Customer&apos;s expense. The Customer may not settle a claim in a manner that admits wrongdoing by, imposes non-monetary obligations on, or fails to fully release Ragusto without Ragusto&apos;s prior written consent.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">23. Limitation of Liability</h2>
        <p className="text-fg-muted leading-relaxed">To the maximum extent permitted by law, Ragusto will not be liable for indirect, incidental, special, exemplary, punitive, or consequential damages; lost profits, revenue, opportunities, goodwill, or data; business interruption; or costs of substitute services.</p>
        <p className="text-fg-muted leading-relaxed">For paid Services, Ragusto&apos;s total aggregate liability for all claims arising from the affected Service, under every theory of liability and in the aggregate, will not exceed the greater of: (a) the fees actually paid by the Customer for that Service during the six months immediately preceding the event giving rise to the claim; and (b) CAD $1,000. For an unpaid preview before any paid Service is activated, Ragusto&apos;s aggregate liability will not exceed CAD $100.</p>
        <p className="text-fg-muted leading-relaxed">The limitations do not apply to fraud, wilful misconduct, liability that cannot legally be limited, the Customer&apos;s payment obligations, or the Customer&apos;s indemnity obligations. Third-party platform failures, Customer-controlled accounts, Customer Content, Customer credentials, and unauthorized changes are outside Ragusto&apos;s responsibility except to the extent directly caused by Ragusto&apos;s breach of an express obligation.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">24. Suspension and Termination</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto may suspend Services for overdue payment, fraud, unlawful activity, abuse, infringement, security threats, excessive risk, or material breach. Where reasonably practicable, Ragusto will provide notice and an opportunity to cure. Suspension does not by itself terminate the Agreement or waive payment obligations.</p>
        <p className="text-fg-muted leading-relaxed">Either party may terminate for the other party&apos;s material breach if the breach is not cured within 15 days after written notice, except that Ragusto may act immediately where reasonably necessary for security, legal compliance, or protection of persons or systems.</p>
        <p className="text-fg-muted leading-relaxed">If the Customer requests early termination during the Initial Term without Ragusto breach, the Minimum Committed Fees remain payable as provided in Section 7 unless Ragusto agrees to a written release or reduced early-termination amount.</p>
        <p className="text-fg-muted leading-relaxed">If Ragusto terminates for the Customer&apos;s uncured material breach, the payment treatment in Section 7 applies. If the Customer terminates for Ragusto&apos;s uncured material breach, or Ragusto terminates without Customer breach, no future Minimum Committed Fees accrue after the effective termination date.</p>
        <p className="text-fg-muted leading-relaxed">A separate Application or domain service may be terminated independently only if its Product Description or a written confirmation from Ragusto permits independent cancellation. Termination of one Service does not automatically terminate another unless the Services are clearly identified as dependent.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">25. Effect of Termination</h2>
        <p className="text-fg-muted leading-relaxed">When a hosted Service ends, the Customer&apos;s licence to use it ends and Ragusto may take it offline, disable access, stop hosting, and cease support. Accrued amounts remain payable.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto is not required to provide proprietary source code, repositories, development tools, reusable components, deployment systems, or third-party materials that cannot lawfully be transferred.</p>
        <p className="text-fg-muted leading-relaxed">Domain transfer rights continue under Section 14. The Customer should request available Customer Content or Customer Service Data exports before termination or within the stated transition period.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">26. Optional Website or Application Buyout</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto is not required to sell or transfer source code. At the Customer&apos;s request, Ragusto may offer a separate written buyout identifying the price, included and excluded materials, third-party licence restrictions, transfer assistance, post-transfer support, and rights retained by Ragusto.</p>
        <p className="text-fg-muted leading-relaxed">No ownership transfer occurs unless a separate written assignment or buyout agreement expressly states the assets transferred and is signed by Ragusto.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">27. Subcontractors, Chain of Title, Independent Contractor, and Assignment</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto may use employees, independent contractors, and service providers to perform the Services and remains responsible for its express contractual obligations subject to this Agreement.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will use written contractor or contributor terms reasonably intended to protect confidentiality and to assign to Ragusto, or otherwise secure for Ragusto, rights sufficient to provide and license the applicable deliverables. Where applicable, those terms may address moral rights, third-party materials, open-source components, and restrictions on unlicensed content.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto is an independent contractor. The Agreement does not create a partnership, employment, fiduciary, or joint-venture relationship.</p>
        <p className="text-fg-muted leading-relaxed">The Customer may not assign the Agreement without Ragusto&apos;s written consent. Ragusto may assign it in connection with a sale, reorganization, or transfer of all or a material part of the business if the successor assumes the material obligations.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">28. Force Majeure</h2>
        <p className="text-fg-muted leading-relaxed">Neither party is liable for delay or failure caused by events beyond reasonable control, including natural disasters, fire, flood, war, civil unrest, governmental action, labour disruption, Internet or utility failure, widespread cyberattack, or third-party infrastructure, registrar, registry, or hosting failure. Payment obligations for Services already provided or made available are not excused.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">29. Notices</h2>
        <p className="text-fg-muted leading-relaxed">
          Contractual notices to the Customer may be sent to the email address in the Customer&apos;s Stripe account, invoice, or most recent correspondence. Notices to Ragusto may be sent to{" "}
          <a className={linkClass} href={`mailto:${SITE.email}`}>jacob@ragusto.com</a>. Cancellation and domain-transfer requests must clearly identify the Customer, applicable Service, and requested effective date.
        </p>
        <p className="text-fg-muted leading-relaxed">Email notice is considered received on the next business day after sending unless the sender receives a delivery-failure notice. A party must keep its contact information current.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">30. Governing Law and Disputes</h2>
        <p className="text-fg-muted leading-relaxed">The Agreement is governed by the laws of Ontario and the federal laws of Canada applicable in Ontario, without regard to conflict-of-law rules.</p>
        <p className="text-fg-muted leading-relaxed">The parties will first attempt in good faith to resolve a dispute through direct discussion. If not resolved, the parties submit to the exclusive jurisdiction of the courts of Ontario sitting in the judicial region in which Ragusto principally carries on business, unless the parties agree in writing to mediation or another process.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">31. General Terms</h2>
        <p className="text-fg-muted leading-relaxed">This Agreement, the applicable Product Description in effect when the Customer completes the applicable checkout or pays the applicable invoice, the checkout or hosted invoice page, the invoice, and written confirmations issued by Ragusto form the entire agreement for the Services and replace prior discussions about the same subject. Amendments must be in writing and accepted by both parties.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may update standard terms for future renewal periods by providing reasonable notice. Material changes will not retroactively alter the Initial Term without Customer agreement except where reasonably necessary for law, security, abuse prevention, or third-party requirements.</p>
        <p className="text-fg-muted leading-relaxed">If a provision is unenforceable, it will be modified to the minimum extent necessary or severed, and the remaining provisions continue. Failure to enforce a provision is not a waiver. Provisions concerning payment, ownership, confidentiality, data, indemnity, liability, domain transfer, and disputes survive termination.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">Schedule 1 - Data Processing Addendum</h2>
        <p className="text-fg-muted leading-relaxed">This Data Processing Addendum applies when Ragusto processes Customer Service Data on behalf of the Customer in connection with a Website or Application. The Customer determines the purposes and essential means of processing, and Ragusto processes the data as a service provider according to this Agreement, the applicable Product Description, and the Customer&apos;s documented lawful instructions.</p>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for the lawfulness, accuracy, and transparency of its collection and use of Customer Service Data, including required notices, consent, legal authority, retention instructions, access controls, and responses to individuals. Ragusto may decline an instruction that it reasonably believes is unlawful, insecure, outside scope, or technically impracticable.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will limit access to personnel and contractors who require access for the Services and who are subject to confidentiality obligations. Ragusto may use subprocessors for hosting, databases, email delivery, payment processing, domain services, security, monitoring, support, and related infrastructure. Ragusto remains responsible for its contractual obligations and will use reasonable measures to require appropriate protection from subprocessors.</p>
        <p className="text-fg-muted leading-relaxed">Customer Service Data may be processed outside Ontario or Canada where required by an applicable provider. Ragusto will use contractual, organizational, or other reasonable measures to require appropriate protection, but data may remain subject to the laws of the jurisdiction in which it is processed.</p>
        <p className="text-fg-muted leading-relaxed">Taking into account the nature of the Services and information reasonably available, Ragusto will provide reasonable assistance with access, correction, deletion, security, or regulatory requests relating to Customer Service Data. Work beyond ordinary support may be billable unless caused by Ragusto&apos;s breach.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto will notify the Customer of a qualifying incident as described in Section 15 and will provide reasonably available information needed for the Customer&apos;s assessment. Ragusto will not notify affected individuals or regulators on the Customer&apos;s behalf unless legally required or separately agreed in writing.</p>
        <p className="text-fg-muted leading-relaxed">At termination, Ragusto will return or delete reasonably accessible Customer Service Data as described in the Agreement, subject to legal obligations, routine backups, security records, and technical limitations. The Customer is responsible for requesting and verifying any required export before the transition period ends.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may provide reasonable documentation of its relevant practices instead of permitting intrusive audits. Any requested audit must be proportionate, protect other customers and security information, occur no more than once annually unless required after a material incident, and be at the Customer&apos;s expense unless it identifies a material Ragusto breach.</p>
      </section>
      <section className="space-y-4">
        <h2 className="legal-section-title">Schedule 2 - Baseline Security Schedule</h2>
        <p className="text-fg-muted leading-relaxed">Ragusto will maintain reasonable administrative, technical, and organizational safeguards appropriate to the nature of the Services and the sensitivity of Customer Service Data. Safeguards are risk-based and may evolve as providers, threats, and technologies change.</p>
        <p className="text-fg-muted leading-relaxed">Baseline measures may include role-appropriate access controls; unique accounts; multi-factor authentication where available and appropriate; secure credential handling; least-privilege access; encrypted transmission through standard protocols; encryption at rest where supported by the applicable provider; software and dependency updates; logging or monitoring appropriate to the service; backups or recovery features where included; and incident-response procedures.</p>
        <p className="text-fg-muted leading-relaxed">Ragusto may rely on security controls supplied by reputable hosting, database, payment, email, registrar, and infrastructure providers. The Customer acknowledges that no safeguard eliminates all risk and that Ragusto does not warrant absolute security, uninterrupted availability, or recovery of every item of data.</p>
        <p className="text-fg-muted leading-relaxed">The Customer is responsible for security of Customer-controlled accounts, devices, users, credentials, data exports, configurations, and third-party services. The Customer must promptly revoke access for departed personnel, use multi-factor authentication where available, and notify Ragusto of suspected compromise.</p>
        <p className="text-fg-muted leading-relaxed">Unless Ragusto expressly approves otherwise in a separate written data-protection agreement, the Services are not designed for medical records, government identification numbers, full payment-card data, financial-account credentials, precise biometrics, information about minors, or other highly sensitive or regulated data.</p>
      </section>
      {"\n"}
      <nav aria-label="Page navigation">
        <Link href="/" className="inline-block text-sm text-fg-muted hover:text-fg">
          ← Back home
        </Link>
      </nav>
    </div>
  );
}
